[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic_integer_array"
path = "src/basic_integer_array.rs"

[[bin]]
name = "equation"
path = "src/equation.rs"

[[bin]]
name = "maze_server"
path = "src/maze_server.rs"

[[bin]]
name = "tower_defence"
path = "src/tower_defence_main.rs"

[[bin]]
name = "tower_defence_hp_search"
path = "src/tower_defence_hp_search.rs"

[[bin]]
name = "tower_defence_server"
path = "src/tower_defence_server.rs"

[[bin]]
name = "swarm"
path = "src/swarm_main.rs"

[[bin]]
name = "swarm_server"
path = "src/swarm_server.rs"

[dependencies]
rayon.workspace = true
rand.workspace = true
ga = {path = "../ga"}
serde_json.workspace = true
serde.workspace = true
toml.workspace = true
axum = "0.7"
tokio = { version = "1", features = ["full"] }
