[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic_integer_array"
path = "src/basic_integer_array.rs"

[[bin]]
name = "equation"
path = "src/equation.rs"

[[bin]]
name = "image_approximation"
path = "src/image_approximation.rs"

[dependencies]
rand.workspace = true
ga = {path = "../ga"}
serde_json.workspace = true
serde.workspace = true
toml.workspace = true
image.workspace = true
